### ISSUE TITLE
[Feature] 转发消息时附带翻译

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [xxtg666/nonebot-plugin-discord-message-bridge#8]
![图片](https://github.com/user-attachments/assets/33d06c3b-bf4d-49f6-870e-91a5fe55a514)

**Comment by xxtg666** [comment]
我认为这不是一个转发插件所要做的功能
电脑端用户可使用 (沉浸式翻译)[https://immersivetranslate.com/]自动显示消息译文
